### ISSUE TITLE
What do the symbols mean?

### ISSUE THREAD

**Issue by letmaik** [alexandrudima/vscode-lcov#1]
There are several symbols and highlightings. It would be good if there was some documentation on what they actually mean.

**Comment by alexandrudima** [comment]
I've updated the README with lots of branch coverage examples (as generated by istanbul)

**Comment by letmaik** [comment]
Great, that's useful. I like that there are two detail modes and that simple is default now, however I think the simple mode doesn't really need symbols at all. Is there a case where they provide information that you can't see from the shading itself?

**Comment by alexandrudima** [comment]
@letmaik Yes, like this one for example:

![image](https://cloud.githubusercontent.com/assets/5047891/18410029/e4f38b9a-7756-11e6-99e4-6493a69070c2.png)

The else branch is missing and line coverage will report this file as fully covered even if only the if branch is taken. Branch coverage points out that the else branch was missed.

**Comment by alexandrudima** [comment]
A better example would be:
```js
function sum(a,b) {
  if (a >= 0) {
    return a + b;
  }
}
```

Tested via:
```js
sum(0, 5);
sum(5, -1);
sum(12, 12);
```

Line coverage will report the function as fully covered, but branch coverage will point out that the tests do not cover the else branch.

**Comment by letmaik** [comment]
Makes sense, good examples!
